name: Build deb packages

on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          #- { name: 'xenial', os: 'ubuntu-latest', container: 'wachii/ubuntu-qt:16.04' }
          #- { name: 'bionic', os: 'ubuntu-18.04', container: '' }
          #- { name: 'focal', os: 'ubuntu-20.04', container: '' }
          - { name: 'jammy', os: 'ubuntu-22.04', container: '' }
          
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set options
        run: echo "--enable-gl-x11 --disable-drm --enable-libmpv-shared" > mpv_options

      - name: Compile and build
        run: ./rebuild -j4

      - name: List
        run: ls
        
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: mpv
          path: /home/runner/work/mpv-linuxbuild2/mpv-linuxbuild2/
